-- =============================================================================
-- FIAP X - Schema inicial do banco fiapx_db (PostgreSQL 16)
--
-- O fiap-x-api-service é o dono do schema: o Flyway aplica este script na
-- subida da API. O fiap-x-video-processor apenas lê/atualiza a tabela videos.
-- =============================================================================

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    role        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE videos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_file_name  VARCHAR(255) NOT NULL,
    stored_file_name    VARCHAR(255) NOT NULL,
    file_path           VARCHAR(255) NOT NULL,
    zip_path            VARCHAR(255),
    file_size           BIGINT,
    frame_count         INTEGER,
    status              VARCHAR(255) NOT NULL,
    -- TEXT: mensagens de erro do FFmpeg podem passar de 255 caracteres
    error_message       TEXT,
    user_id             BIGINT       NOT NULL,
    created_at          TIMESTAMP(6) NOT NULL,
    processed_at        TIMESTAMP(6),
    CONSTRAINT fk_videos_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_videos_status CHECK (status IN ('RECEBIDO', 'PROCESSANDO', 'CONCLUIDO', 'ERRO'))
);

-- Listagem de vídeos por usuário (GET /api/videos)
CREATE INDEX idx_videos_user_id_created_at ON videos (user_id, created_at DESC);
